declare module 'androidtv-remote' {

    /** Declaration file generated by dts-gen */
    export class AndroidRemote {
        constructor(...args: any[]);

        getCertificate(...args: any[]): void;

        sendAppLink(...args: any[]): void;

        sendCode(...args: any[]): void;

        sendKey(...args: any[]): void;

        sendPower(...args: any[]): void;

        start(...args: any[]): void;

        stop(...args: any[]): void;

        static captureRejectionSymbol: any;

        static captureRejections: boolean;

        static defaultMaxListeners: number;

        static errorMonitor: any;

        static getEventListeners(emitterOrTarget: any, type: any): any;

        static init(opts: any): void;

        static kMaxEventTargetListeners: any;

        static kMaxEventTargetListenersWarned: any;

        static listenerCount(emitter: any, type: any): any;

        static on(emitter: any, event: any, options: any): any;

        static once(emitter: any, name: any, options: any): any;

        static setMaxListeners(n: any, eventTargets: any): void;

        static usingDomains: boolean;

    }

    export const RemoteDirection: {
        "0": string;
        "1": string;
        "2": string;
        "3": string;
        END_LONG: number;
        SHORT: number;
        START_LONG: number;
        UNKNOWN_DIRECTION: number;
    };

    export const RemoteKeyCode: {
        "0": string;
        "1": string;
        "10": string;
        "100": string;
        "101": string;
        "102": string;
        "103": string;
        "104": string;
        "105": string;
        "106": string;
        "107": string;
        "108": string;
        "109": string;
        "11": string;
        "110": string;
        "111": string;
        "112": string;
        "113": string;
        "114": string;
        "115": string;
        "116": string;
        "117": string;
        "118": string;
        "119": string;
        "12": string;
        "120": string;
        "121": string;
        "122": string;
        "123": string;
        "124": string;
        "125": string;
        "126": string;
        "127": string;
        "128": string;
        "129": string;
        "13": string;
        "130": string;
        "131": string;
        "132": string;
        "133": string;
        "134": string;
        "135": string;
        "136": string;
        "137": string;
        "138": string;
        "139": string;
        "14": string;
        "140": string;
        "141": string;
        "142": string;
        "143": string;
        "144": string;
        "145": string;
        "146": string;
        "147": string;
        "148": string;
        "149": string;
        "15": string;
        "150": string;
        "151": string;
        "152": string;
        "153": string;
        "154": string;
        "155": string;
        "156": string;
        "157": string;
        "158": string;
        "159": string;
        "16": string;
        "160": string;
        "161": string;
        "162": string;
        "163": string;
        "164": string;
        "165": string;
        "166": string;
        "167": string;
        "168": string;
        "169": string;
        "17": string;
        "170": string;
        "171": string;
        "172": string;
        "173": string;
        "174": string;
        "175": string;
        "176": string;
        "177": string;
        "178": string;
        "179": string;
        "18": string;
        "180": string;
        "181": string;
        "182": string;
        "183": string;
        "184": string;
        "185": string;
        "186": string;
        "187": string;
        "188": string;
        "189": string;
        "19": string;
        "190": string;
        "191": string;
        "192": string;
        "193": string;
        "194": string;
        "195": string;
        "196": string;
        "197": string;
        "198": string;
        "199": string;
        "2": string;
        "20": string;
        "200": string;
        "201": string;
        "202": string;
        "203": string;
        "204": string;
        "205": string;
        "206": string;
        "207": string;
        "208": string;
        "209": string;
        "21": string;
        "210": string;
        "211": string;
        "212": string;
        "213": string;
        "214": string;
        "215": string;
        "216": string;
        "217": string;
        "218": string;
        "219": string;
        "22": string;
        "220": string;
        "221": string;
        "222": string;
        "223": string;
        "224": string;
        "225": string;
        "226": string;
        "227": string;
        "228": string;
        "229": string;
        "23": string;
        "230": string;
        "231": string;
        "232": string;
        "233": string;
        "234": string;
        "235": string;
        "236": string;
        "237": string;
        "238": string;
        "239": string;
        "24": string;
        "240": string;
        "241": string;
        "242": string;
        "243": string;
        "244": string;
        "245": string;
        "246": string;
        "247": string;
        "248": string;
        "249": string;
        "25": string;
        "250": string;
        "251": string;
        "252": string;
        "253": string;
        "254": string;
        "255": string;
        "256": string;
        "257": string;
        "258": string;
        "259": string;
        "26": string;
        "260": string;
        "261": string;
        "262": string;
        "263": string;
        "264": string;
        "265": string;
        "266": string;
        "267": string;
        "268": string;
        "269": string;
        "27": string;
        "270": string;
        "271": string;
        "272": string;
        "273": string;
        "274": string;
        "275": string;
        "276": string;
        "277": string;
        "278": string;
        "279": string;
        "28": string;
        "280": string;
        "281": string;
        "282": string;
        "283": string;
        "284": string;
        "285": string;
        "286": string;
        "287": string;
        "288": string;
        "289": string;
        "29": string;
        "290": string;
        "291": string;
        "292": string;
        "293": string;
        "294": string;
        "295": string;
        "296": string;
        "297": string;
        "298": string;
        "299": string;
        "3": string;
        "30": string;
        "300": string;
        "301": string;
        "302": string;
        "303": string;
        "304": string;
        "31": string;
        "32": string;
        "33": string;
        "34": string;
        "35": string;
        "36": string;
        "37": string;
        "38": string;
        "39": string;
        "4": string;
        "40": string;
        "41": string;
        "42": string;
        "43": string;
        "44": string;
        "45": string;
        "46": string;
        "47": string;
        "48": string;
        "49": string;
        "5": string;
        "50": string;
        "51": string;
        "52": string;
        "53": string;
        "54": string;
        "55": string;
        "56": string;
        "57": string;
        "58": string;
        "59": string;
        "6": string;
        "60": string;
        "61": string;
        "62": string;
        "63": string;
        "64": string;
        "65": string;
        "66": string;
        "67": string;
        "68": string;
        "69": string;
        "7": string;
        "70": string;
        "71": string;
        "72": string;
        "73": string;
        "74": string;
        "75": string;
        "76": string;
        "77": string;
        "78": string;
        "79": string;
        "8": string;
        "80": string;
        "81": string;
        "82": string;
        "83": string;
        "84": string;
        "85": string;
        "86": string;
        "87": string;
        "88": string;
        "89": string;
        "9": string;
        "90": string;
        "91": string;
        "92": string;
        "93": string;
        "94": string;
        "95": string;
        "96": string;
        "97": string;
        "98": string;
        "99": string;
        KEYCODE_0: number;
        KEYCODE_1: number;
        KEYCODE_11: number;
        KEYCODE_12: number;
        KEYCODE_2: number;
        KEYCODE_3: number;
        KEYCODE_3D_MODE: number;
        KEYCODE_4: number;
        KEYCODE_5: number;
        KEYCODE_6: number;
        KEYCODE_7: number;
        KEYCODE_8: number;
        KEYCODE_9: number;
        KEYCODE_A: number;
        KEYCODE_ALL_APPS: number;
        KEYCODE_ALT_LEFT: number;
        KEYCODE_ALT_RIGHT: number;
        KEYCODE_APOSTROPHE: number;
        KEYCODE_APP_SWITCH: number;
        KEYCODE_ASSIST: number;
        KEYCODE_AT: number;
        KEYCODE_AVR_INPUT: number;
        KEYCODE_AVR_POWER: number;
        KEYCODE_B: number;
        KEYCODE_BACK: number;
        KEYCODE_BACKSLASH: number;
        KEYCODE_BOOKMARK: number;
        KEYCODE_BREAK: number;
        KEYCODE_BRIGHTNESS_DOWN: number;
        KEYCODE_BRIGHTNESS_UP: number;
        KEYCODE_BUTTON_1: number;
        KEYCODE_BUTTON_10: number;
        KEYCODE_BUTTON_11: number;
        KEYCODE_BUTTON_12: number;
        KEYCODE_BUTTON_13: number;
        KEYCODE_BUTTON_14: number;
        KEYCODE_BUTTON_15: number;
        KEYCODE_BUTTON_16: number;
        KEYCODE_BUTTON_2: number;
        KEYCODE_BUTTON_3: number;
        KEYCODE_BUTTON_4: number;
        KEYCODE_BUTTON_5: number;
        KEYCODE_BUTTON_6: number;
        KEYCODE_BUTTON_7: number;
        KEYCODE_BUTTON_8: number;
        KEYCODE_BUTTON_9: number;
        KEYCODE_BUTTON_A: number;
        KEYCODE_BUTTON_B: number;
        KEYCODE_BUTTON_C: number;
        KEYCODE_BUTTON_L1: number;
        KEYCODE_BUTTON_L2: number;
        KEYCODE_BUTTON_MODE: number;
        KEYCODE_BUTTON_R1: number;
        KEYCODE_BUTTON_R2: number;
        KEYCODE_BUTTON_SELECT: number;
        KEYCODE_BUTTON_START: number;
        KEYCODE_BUTTON_THUMBL: number;
        KEYCODE_BUTTON_THUMBR: number;
        KEYCODE_BUTTON_X: number;
        KEYCODE_BUTTON_Y: number;
        KEYCODE_BUTTON_Z: number;
        KEYCODE_C: number;
        KEYCODE_CALCULATOR: number;
        KEYCODE_CALENDAR: number;
        KEYCODE_CALL: number;
        KEYCODE_CAMERA: number;
        KEYCODE_CAPS_LOCK: number;
        KEYCODE_CAPTIONS: number;
        KEYCODE_CHANNEL_DOWN: number;
        KEYCODE_CHANNEL_UP: number;
        KEYCODE_CLEAR: number;
        KEYCODE_COMMA: number;
        KEYCODE_CONTACTS: number;
        KEYCODE_COPY: number;
        KEYCODE_CTRL_LEFT: number;
        KEYCODE_CTRL_RIGHT: number;
        KEYCODE_CUT: number;
        KEYCODE_D: number;
        KEYCODE_DEL: number;
        KEYCODE_DEMO_APP_1: number;
        KEYCODE_DEMO_APP_2: number;
        KEYCODE_DEMO_APP_3: number;
        KEYCODE_DEMO_APP_4: number;
        KEYCODE_DPAD_CENTER: number;
        KEYCODE_DPAD_DOWN: number;
        KEYCODE_DPAD_DOWN_LEFT: number;
        KEYCODE_DPAD_DOWN_RIGHT: number;
        KEYCODE_DPAD_LEFT: number;
        KEYCODE_DPAD_RIGHT: number;
        KEYCODE_DPAD_UP: number;
        KEYCODE_DPAD_UP_LEFT: number;
        KEYCODE_DPAD_UP_RIGHT: number;
        KEYCODE_DVR: number;
        KEYCODE_E: number;
        KEYCODE_EISU: number;
        KEYCODE_ENDCALL: number;
        KEYCODE_ENTER: number;
        KEYCODE_ENVELOPE: number;
        KEYCODE_EQUALS: number;
        KEYCODE_ESCAPE: number;
        KEYCODE_EXPLORER: number;
        KEYCODE_F: number;
        KEYCODE_F1: number;
        KEYCODE_F10: number;
        KEYCODE_F11: number;
        KEYCODE_F12: number;
        KEYCODE_F2: number;
        KEYCODE_F3: number;
        KEYCODE_F4: number;
        KEYCODE_F5: number;
        KEYCODE_F6: number;
        KEYCODE_F7: number;
        KEYCODE_F8: number;
        KEYCODE_F9: number;
        KEYCODE_FEATURED_APP_1: number;
        KEYCODE_FEATURED_APP_2: number;
        KEYCODE_FEATURED_APP_3: number;
        KEYCODE_FEATURED_APP_4: number;
        KEYCODE_FOCUS: number;
        KEYCODE_FORWARD: number;
        KEYCODE_FORWARD_DEL: number;
        KEYCODE_FUNCTION: number;
        KEYCODE_G: number;
        KEYCODE_GRAVE: number;
        KEYCODE_GUIDE: number;
        KEYCODE_H: number;
        KEYCODE_HEADSETHOOK: number;
        KEYCODE_HELP: number;
        KEYCODE_HENKAN: number;
        KEYCODE_HOME: number;
        KEYCODE_I: number;
        KEYCODE_INFO: number;
        KEYCODE_INSERT: number;
        KEYCODE_J: number;
        KEYCODE_K: number;
        KEYCODE_KANA: number;
        KEYCODE_KATAKANA_HIRAGANA: number;
        KEYCODE_L: number;
        KEYCODE_LANGUAGE_SWITCH: number;
        KEYCODE_LAST_CHANNEL: number;
        KEYCODE_LEFT_BRACKET: number;
        KEYCODE_M: number;
        KEYCODE_MANNER_MODE: number;
        KEYCODE_MEDIA_AUDIO_TRACK: number;
        KEYCODE_MEDIA_CLOSE: number;
        KEYCODE_MEDIA_EJECT: number;
        KEYCODE_MEDIA_FAST_FORWARD: number;
        KEYCODE_MEDIA_NEXT: number;
        KEYCODE_MEDIA_PAUSE: number;
        KEYCODE_MEDIA_PLAY: number;
        KEYCODE_MEDIA_PLAY_PAUSE: number;
        KEYCODE_MEDIA_PREVIOUS: number;
        KEYCODE_MEDIA_RECORD: number;
        KEYCODE_MEDIA_REWIND: number;
        KEYCODE_MEDIA_SKIP_BACKWARD: number;
        KEYCODE_MEDIA_SKIP_FORWARD: number;
        KEYCODE_MEDIA_STEP_BACKWARD: number;
        KEYCODE_MEDIA_STEP_FORWARD: number;
        KEYCODE_MEDIA_STOP: number;
        KEYCODE_MEDIA_TOP_MENU: number;
        KEYCODE_MENU: number;
        KEYCODE_META_LEFT: number;
        KEYCODE_META_RIGHT: number;
        KEYCODE_MINUS: number;
        KEYCODE_MOVE_END: number;
        KEYCODE_MOVE_HOME: number;
        KEYCODE_MUHENKAN: number;
        KEYCODE_MUSIC: number;
        KEYCODE_MUTE: number;
        KEYCODE_N: number;
        KEYCODE_NAVIGATE_IN: number;
        KEYCODE_NAVIGATE_NEXT: number;
        KEYCODE_NAVIGATE_OUT: number;
        KEYCODE_NAVIGATE_PREVIOUS: number;
        KEYCODE_NOTIFICATION: number;
        KEYCODE_NUM: number;
        KEYCODE_NUMPAD_0: number;
        KEYCODE_NUMPAD_1: number;
        KEYCODE_NUMPAD_2: number;
        KEYCODE_NUMPAD_3: number;
        KEYCODE_NUMPAD_4: number;
        KEYCODE_NUMPAD_5: number;
        KEYCODE_NUMPAD_6: number;
        KEYCODE_NUMPAD_7: number;
        KEYCODE_NUMPAD_8: number;
        KEYCODE_NUMPAD_9: number;
        KEYCODE_NUMPAD_ADD: number;
        KEYCODE_NUMPAD_COMMA: number;
        KEYCODE_NUMPAD_DIVIDE: number;
        KEYCODE_NUMPAD_DOT: number;
        KEYCODE_NUMPAD_ENTER: number;
        KEYCODE_NUMPAD_EQUALS: number;
        KEYCODE_NUMPAD_LEFT_PAREN: number;
        KEYCODE_NUMPAD_MULTIPLY: number;
        KEYCODE_NUMPAD_RIGHT_PAREN: number;
        KEYCODE_NUMPAD_SUBTRACT: number;
        KEYCODE_NUM_LOCK: number;
        KEYCODE_O: number;
        KEYCODE_P: number;
        KEYCODE_PAGE_DOWN: number;
        KEYCODE_PAGE_UP: number;
        KEYCODE_PAIRING: number;
        KEYCODE_PASTE: number;
        KEYCODE_PERIOD: number;
        KEYCODE_PICTSYMBOLS: number;
        KEYCODE_PLUS: number;
        KEYCODE_POUND: number;
        KEYCODE_POWER: number;
        KEYCODE_PROFILE_SWITCH: number;
        KEYCODE_PROG_BLUE: number;
        KEYCODE_PROG_GREEN: number;
        KEYCODE_PROG_RED: number;
        KEYCODE_PROG_YELLOW: number;
        KEYCODE_Q: number;
        KEYCODE_R: number;
        KEYCODE_REFRESH: number;
        KEYCODE_RIGHT_BRACKET: number;
        KEYCODE_RO: number;
        KEYCODE_S: number;
        KEYCODE_SCROLL_LOCK: number;
        KEYCODE_SEARCH: number;
        KEYCODE_SEMICOLON: number;
        KEYCODE_SETTINGS: number;
        KEYCODE_SHIFT_LEFT: number;
        KEYCODE_SHIFT_RIGHT: number;
        KEYCODE_SLASH: number;
        KEYCODE_SLEEP: number;
        KEYCODE_SOFT_LEFT: number;
        KEYCODE_SOFT_RIGHT: number;
        KEYCODE_SOFT_SLEEP: number;
        KEYCODE_SPACE: number;
        KEYCODE_STAR: number;
        KEYCODE_STB_INPUT: number;
        KEYCODE_STB_POWER: number;
        KEYCODE_STEM_1: number;
        KEYCODE_STEM_2: number;
        KEYCODE_STEM_3: number;
        KEYCODE_STEM_PRIMARY: number;
        KEYCODE_SWITCH_CHARSET: number;
        KEYCODE_SYM: number;
        KEYCODE_SYSRQ: number;
        KEYCODE_SYSTEM_NAVIGATION_DOWN: number;
        KEYCODE_SYSTEM_NAVIGATION_LEFT: number;
        KEYCODE_SYSTEM_NAVIGATION_RIGHT: number;
        KEYCODE_SYSTEM_NAVIGATION_UP: number;
        KEYCODE_T: number;
        KEYCODE_TAB: number;
        KEYCODE_THUMBS_DOWN: number;
        KEYCODE_THUMBS_UP: number;
        KEYCODE_TV: number;
        KEYCODE_TV_ANTENNA_CABLE: number;
        KEYCODE_TV_AUDIO_DESCRIPTION: number;
        KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN: number;
        KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP: number;
        KEYCODE_TV_CONTENTS_MENU: number;
        KEYCODE_TV_DATA_SERVICE: number;
        KEYCODE_TV_INPUT: number;
        KEYCODE_TV_INPUT_COMPONENT_1: number;
        KEYCODE_TV_INPUT_COMPONENT_2: number;
        KEYCODE_TV_INPUT_COMPOSITE_1: number;
        KEYCODE_TV_INPUT_COMPOSITE_2: number;
        KEYCODE_TV_INPUT_HDMI_1: number;
        KEYCODE_TV_INPUT_HDMI_2: number;
        KEYCODE_TV_INPUT_HDMI_3: number;
        KEYCODE_TV_INPUT_HDMI_4: number;
        KEYCODE_TV_INPUT_VGA_1: number;
        KEYCODE_TV_MEDIA_CONTEXT_MENU: number;
        KEYCODE_TV_NETWORK: number;
        KEYCODE_TV_NUMBER_ENTRY: number;
        KEYCODE_TV_POWER: number;
        KEYCODE_TV_RADIO_SERVICE: number;
        KEYCODE_TV_SATELLITE: number;
        KEYCODE_TV_SATELLITE_BS: number;
        KEYCODE_TV_SATELLITE_CS: number;
        KEYCODE_TV_SATELLITE_SERVICE: number;
        KEYCODE_TV_TELETEXT: number;
        KEYCODE_TV_TERRESTRIAL_ANALOG: number;
        KEYCODE_TV_TERRESTRIAL_DIGITAL: number;
        KEYCODE_TV_TIMER_PROGRAMMING: number;
        KEYCODE_TV_ZOOM_MODE: number;
        KEYCODE_U: number;
        KEYCODE_UNKNOWN: number;
        KEYCODE_V: number;
        KEYCODE_VIDEO_APP_1: number;
        KEYCODE_VIDEO_APP_2: number;
        KEYCODE_VIDEO_APP_3: number;
        KEYCODE_VIDEO_APP_4: number;
        KEYCODE_VIDEO_APP_5: number;
        KEYCODE_VIDEO_APP_6: number;
        KEYCODE_VIDEO_APP_7: number;
        KEYCODE_VIDEO_APP_8: number;
        KEYCODE_VOICE_ASSIST: number;
        KEYCODE_VOLUME_DOWN: number;
        KEYCODE_VOLUME_MUTE: number;
        KEYCODE_VOLUME_UP: number;
        KEYCODE_W: number;
        KEYCODE_WAKEUP: number;
        KEYCODE_WINDOW: number;
        KEYCODE_X: number;
        KEYCODE_Y: number;
        KEYCODE_YEN: number;
        KEYCODE_Z: number;
        KEYCODE_ZENKAKU_HANKAKU: number;
        KEYCODE_ZOOM_IN: number;
        KEYCODE_ZOOM_OUT: number;
    };

    export namespace AndroidRemote {
        class EventEmitter {
            constructor(opts: any);

            addListener(type: any, listener: any): any;

            emit(type: any, args: any): any;

            eventNames(): any;

            getMaxListeners(): any;

            listenerCount(type: any): any;

            listeners(type: any): any;

            off(type: any, listener: any): any;

            on(type: any, listener: any): any;

            once(type: any, listener: any): any;

            prependListener(type: any, listener: any): any;

            prependOnceListener(type: any, listener: any): any;

            rawListeners(type: any): any;

            removeAllListeners(type: any, ...args: any[]): any;

            removeListener(type: any, listener: any): any;

            setMaxListeners(n: any): any;

            static EventEmitter: any;

            static captureRejectionSymbol: any;

            static captureRejections: boolean;

            static defaultMaxListeners: number;

            static errorMonitor: any;

            static getEventListeners(emitterOrTarget: any, type: any): any;

            static init(opts: any): void;

            static kMaxEventTargetListeners: any;

            static kMaxEventTargetListenersWarned: any;

            static listenerCount(emitter: any, type: any): any;

            static on(emitter: any, event: any, options: any): any;

            static once(emitter: any, name: any, options: any): any;

            static setMaxListeners(n: any, eventTargets: any): void;

            static usingDomains: boolean;

        }

        class EventEmitterAsyncResource {
            constructor(...args: any[]);

            emit(...args: any[]): void;

            emitDestroy(...args: any[]): void;

            static EventEmitterAsyncResource: any;

            static captureRejectionSymbol: any;

            static captureRejections: boolean;

            static defaultMaxListeners: number;

            static errorMonitor: any;

            static getEventListeners(emitterOrTarget: any, type: any): any;

            static init(opts: any): void;

            static kMaxEventTargetListeners: any;

            static kMaxEventTargetListenersWarned: any;

            static listenerCount(emitter: any, type: any): any;

            static on(emitter: any, event: any, options: any): any;

            static once(emitter: any, name: any, options: any): any;

            static setMaxListeners(n: any, eventTargets: any): void;

            static usingDomains: boolean;

        }

        namespace EventEmitter {
            class EventEmitterAsyncResource {
                constructor(...args: any[]);

                emit(...args: any[]): void;

                emitDestroy(...args: any[]): void;

                static EventEmitter: any;

                static EventEmitterAsyncResource: any;

                static captureRejectionSymbol: any;

                static captureRejections: boolean;

                static defaultMaxListeners: number;

                static errorMonitor: any;

                static getEventListeners(emitterOrTarget: any, type: any): any;

                static init(opts: any): void;

                static kMaxEventTargetListeners: any;

                static kMaxEventTargetListenersWarned: any;

                static listenerCount(emitter: any, type: any): any;

                static on(emitter: any, event: any, options: any): any;

                static once(emitter: any, name: any, options: any): any;

                static setMaxListeners(n: any, eventTargets: any): void;

                static usingDomains: boolean;

            }

        }

        namespace EventEmitterAsyncResource {
            class EventEmitter {
                constructor(opts: any);

                addListener(type: any, listener: any): any;

                emit(type: any, args: any): any;

                eventNames(): any;

                getMaxListeners(): any;

                listenerCount(type: any): any;

                listeners(type: any): any;

                off(type: any, listener: any): any;

                on(type: any, listener: any): any;

                once(type: any, listener: any): any;

                prependListener(type: any, listener: any): any;

                prependOnceListener(type: any, listener: any): any;

                rawListeners(type: any): any;

                removeAllListeners(type: any, ...args: any[]): any;

                removeListener(type: any, listener: any): any;

                setMaxListeners(n: any): any;

                static EventEmitter: any;

                static EventEmitterAsyncResource: any;

                static captureRejectionSymbol: any;

                static captureRejections: boolean;

                static defaultMaxListeners: number;

                static errorMonitor: any;

                static getEventListeners(emitterOrTarget: any, type: any): any;

                static init(opts: any): void;

                static kMaxEventTargetListeners: any;

                static kMaxEventTargetListenersWarned: any;

                static listenerCount(emitter: any, type: any): any;

                static on(emitter: any, event: any, options: any): any;

                static once(emitter: any, name: any, options: any): any;

                static setMaxListeners(n: any, eventTargets: any): void;

                static usingDomains: boolean;

            }

        }

    }
}